# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# apply Azure openvpn security group rules to existing vm
---
- name: POSTGRESQL OVERLAY AZURE | applying postgresql security group
  azure_rm_securitygroup:
    resource_group: "{{ specified_resourcegroup.name }}"
    name: "dnsg_{{ project }}_{{ application }}_public_internal"
    rules:
      - name: AllowPG
        proto: TCP
        destination_port_range: 5432
        access: Allow
        priority: 101
        direction: Inbound
        source_address_prefix: "{{ internal_public_subnet_result.properties.addressPrefix }}"
  register: sg_postgresql