#!/usr/bin/env sh
# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 

: "${AWS_PROFILE:=datanexus}" && export AWS_PROFILE="$AWS_PROFILE"    # sets this to a reasonable ~/.aws/credentials default
: "${AZURE_PROFILE:=datanexus}" && export AZURE_PROFILE="$AZURE_PROFILE"    # sets this to a reasonable ~/.azure/credentials default

if [ "$1" = "-h" ] ; then
    printf "Usage:  cleanup [-h]\\t\\thelp\\n"
    printf "\\tcleanup [aws | osp | FILE]\tuse aws, osp, or FILE configuration file\\n"
    exit 0
fi

if [ $1 = "aws" ] || [ $1 = "osp" ]; then
  export configuration="$1-configuration.yml"
else
  export configuration="$1"
fi

./cleanup-postgresql -e "configuration=$configuration"
