#!/usr/bin/env sh
# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 

export AWS_PROFILE=datanexus    # set this to the desired AWS profile in ~/.aws/credentials

if [ "$1" = "-h" ] ; then
    printf "Usage:  cleanup [-h]\\t\thelp\\n"
    printf "\\tcleanup [aws | osp | FILE]\tuse aws, osp, or FILE configuration file\\n"
    exit 0
fi

if [ $1 = "aws" ] || [ $1 = "osp" ]; then
  export configuration="$1-configuration.yml"
else
  export configuration="$1"
fi

./cleanup-postgresql -e "configuration=$configuration"
