#!/bin/sh
# (c) 2016 DataNexus Inc.  All Rights Reserved.

export AWS_PROFILE=datanexus    # set this to the desired AWS profile in ~/.aws/credentials

if [ "$1" == "-h" ] ; then
    echo "Usage:  `basename $0` [-h]\t\thelp"
    echo "\t`basename $0` [aws | osp | FILE]\ttest either aws, osp, or FILE configuration"
    exit 0
fi

if [ $1 == "aws" ] || [ $1 == "osp" ]; then
  export configuration="$1-configuration.yml"
else
  export configuration="$1"
fi

if [ $1 == "osp" ]; then
  export hostfile="-i `/bin/ls *.hostfile`"
fi

echo "testing instance(s) using $configuration..."
./test-postgresql $hostfile -e "configuration=$configuration"
