# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 
#
# streaming tasks for the replica
---
- block:
    - name: preserving postgresql.conf
      command: /bin/cp {{ postgresql_config_path }}/postgresql.conf /tmp
      become_user: "{{ postgresql_user }}"
       
    - name: Remove data directory in preparation for streaming
      file:
        path: "{{ postgresql_data_dir }}"  
        state: absent

    - name: Ensure PostgreSQL data directory exists.
      file:
        path: "{{ postgresql_data_dir }}"
        owner: "{{ postgresql_user }}"
        group: "{{ postgresql_group }}"
        state: directory
        mode: 0700
    
    - name: ensure PostgreSQL preferences directory exists
      file:
        path: "{{ postgresql_home_dir }}/.postgresql"
        owner: "{{ postgresql_user }}"
        group: "{{ postgresql_group }}"
        state: directory
        mode: 0700      
    
    - name: build postgresql password file
      blockinfile:
        name: "{{ postgresql_home_dir }}/.pgpass"
        mode: 0600
        create: yes
        block: |
          {{ hostvars[groups.postgresql_master.0].postgresql_interface_ipv4 }}:5432:*:replicator:replicator
      become_user: "{{ postgresql_user }}"
              
    - name: copy initial database
      command: /bin/pg_basebackup -h {{ hostvars[item].postgresql_interface_ipv4  }} -D {{ postgresql_data_dir }} -U replicator -v -P --xlog-method=stream
      become_user: "{{ postgresql_user }}"
      with_items: "{{ groups.postgresql_master }}"
      
    - name: Restore postgresql.conf
      command: /bin/cp /tmp/postgresql.conf {{ postgresql_config_path }}
      become_user: "{{ postgresql_user }}"
   
    - name: build recovery file
      blockinfile:
        name: "{{ postgresql_config_path }}/recovery.conf"
        mode: 0600
        create: yes
        block: |
          standby_mode = 'on'
          primary_conninfo = 'host={{ hostvars[item].postgresql_interface_ipv4 }} port=5432 user=replicator password=replicator'
          trigger_file = '/tmp/postgresql.trigger'
      become_user: "{{ postgresql_user }}"
      with_items: "{{ groups.postgresql_master }}"
      
    - name: fixing SE Linux labels on {{ postgresql_data_dir }}
      command: /usr/sbin/fixfiles -F restore "{{ postgresql_data_dir }}"

    - name: configure write ahead log for streaming
      lineinfile:
        dest: "{{ postgresql_config_path }}/postgresql.conf"
        regexp: "^#wal_level"
        backrefs: yes
        line: "wal_level = hot_standby\t\t\t# minimal, archive, or hot_standby"
      notify: restart postgresql

    - name: turn on hot standby
      lineinfile:
        dest: "{{ postgresql_config_path }}/postgresql.conf"
        regexp: "^#hot_standby ="
        backrefs: yes
        line: "hot_standby = on\t\t\t# \"on\" allows queries during recovery"
      notify: restart postgresql

    - name: configure write ahead log senders
      lineinfile:
        dest: "{{ postgresql_config_path }}/postgresql.conf"
        regexp: "^#max_wal_senders"
        backrefs: yes
        line: "max_wal_senders = 3\t\t# max number of walsender processes"
      notify: restart postgresql

    - name: configure checkpoint segments
      lineinfile:
        dest: "{{ postgresql_config_path }}/postgresql.conf"
        regexp: "^#checkpoint_segments"
        backrefs: yes
        line: "checkpoint_segments = 8\t\t\t# logfile segments, min 1, 16MB each"
      notify: restart postgresql

    - name: configure write ahead log keep segments
      lineinfile:
        dest: "{{ postgresql_config_path }}/postgresql.conf"
        regexp: "^#wal_keep_segments"
        backrefs: yes
        line: "wal_keep_segments = 8\t\t# in logfile segments, 16MB each; 0 disables"
      notify: restart postgresql    
  when: inventory_hostname in groups.postgresql_replica
  become: true