# (c) Copyright 2016 DataNexus Inc.  All Rights Reserved. 
#
# streaming roles and tasks for the master
---
postgresql_user: postgres
postgresql_unix_socket_directories:
  - /var/run/postgresql

# add replicator user by default
replication_users:
  - name: replicator # required; the rest are optional
    password: replicator # defaults to not set
#    priv: # defaults to not set
    role_attr_flags: Replication # defaults to not set
#    db: # defaults to not set
#    login_host: # defaults to 'localhost'
#    login_password: # defaults to not set
#    login_user: # defaults to '{{ postgresql_user }}'
#    login_unix_socket: # defaults to 1st of postgresql_unix_socket_directories
#    port: # defaults to not set
#    state: # defaults to 'present
