# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# Apply AWS postgresql security group rules
---
- ec2_instance_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Tenant": "{{ tenant }}"
      "tag:Project": "{{ project }}"
      "tag:Domain": "{{ domain }}"
      "tag:Application": "{{ application }}"
      "tag:Cluster": "{{ cluster | default ('a') }}"
      "tag:Flow": "{{ flow | default ('none') }}"
  register: postgresql_public_interfaces
  when: cloud == 'aws'

# this only works for a multi-interface system
- name: applying {{ application }} security rules to interface 1
  ec2_eni:
    region: "{{ region }}"
    eni_id: "{{ item.network_interfaces.1.network_interface_id }}"
    security_groups: "{{ sg_postgresql.group_id }}"
  with_items: "{{ postgresql_public_interfaces.instances }}"
  when:
    -  postgresql_public_interfaces.instances | length > 0
